AWSTemplateFormatVersion: 2010-09-09
Description: vrms-sam-ocr
Transform:
- AWS::Serverless-2016-10-31
Resources:
  OCRStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri:
        Bucket: vrms-sam-apps
        Key: 48d30d8d5e4f6c5064a08ce9fdb16e74
      DefinitionSubstitutions:
        helloFromLambdaFunctionArn:
          Fn::GetAtt:
          - helloFromLambdaFunction
          - Arn
        helloFromPreprocessorFunctionArn:
          Fn::GetAtt:
          - helloFromPreprocessorFunction
          - Arn
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: helloFromPreprocessorFunction
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello/hello-from-lambda.helloFromLambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      CodeUri: s3://vrms-sam-apps/44b30693ba5955035a67da6d5b7662f3
  helloFromPreprocessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/OCRPreprocess/preprocessor.helloFromPreprocessor
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      CodeUri: s3://vrms-sam-apps/44b30693ba5955035a67da6d5b7662f3
