AWSTemplateFormatVersion: 2010-09-09
Description: vrms-sam-ocr
Transform:
- AWS::Serverless-2016-10-31
Resources:
  OCRStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri:
        Bucket: vrms-sam-apps
        Key: f4b00a0cd14070856db933df2ebb16ba
      DefinitionSubstitutions:
        helloFromLambdaFunctionArn:
          Fn::GetAtt:
          - helloFromLambdaFunction
          - Arn
        helloFromPreprocessorFunctionArn:
          Fn::GetAtt:
          - helloFromPreprocessorFunction
          - Arn
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: helloFromPreprocessorFunction
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello/hello-from-lambda.helloFromLambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      CodeUri: s3://vrms-sam-apps/a810ae20b8010f5d54dfc0992de75674
  helloFromPreprocessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/OCRPreprocess/preprocessor.helloFromPreprocessor
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      CodeUri: s3://vrms-sam-apps/a810ae20b8010f5d54dfc0992de75674
